### ISSUE TITLE
Crashes when launching

### ISSUE THREAD

**Issue by boxingink713994** [doombubbles/mega-knowledge#1]
yes i have tried to troubleshoot my mods, when i removed all my mod it still crashes
[Latest.log](https://github.com/doombubbles/mega-knowledge/files/10927910/Latest.log)
Log attached

**Comment by doombubbles** [comment]
It's crashing because it's the old pre- MelonLoader 0.6 version. Downloading latest should fix.

**Comment by boxingink713994** [comment]
didnt help, reinstalled melonloader and mod manager but still crashes
[Latest.log](https://github.com/doombubbles/mega-knowledge/files/10937892/Latest.log)
log attached

**Comment by doombubbles** [comment]
The log confirms you're still using Mega Knowledge v1.1.0 which is too old to work with MelonLoader 0.6.0

The latest version is 1.1.3 https://github.com/doombubbles/mega-knowledge/releases/tag/1.1.3
